### ISSUE TITLE
No error reported when FaceBox IP or camera entity is invalid

### ISSUE THREAD

**Issue by MimbaMonkeyHouse** [robmarkcole/HASS-Machinebox-Facebox#8]
@robmarkcole this behaviour was noticed on HA 70.1 with stock component and multiple cameras

When an invalid IP setting for FaceBox or a non existing camera entity is declared, no error is reported and a new entity is created as normal.
Here is a sample code as an example:
```
  - platform: facebox
    ip_address: 192.168.1.1
    port: 8080
    source:
      - entity_id: camera.nocam
        name: Nocam
```
And here is the new entity created with no error in the log:
```
image_processing.nocam	
state: unknown	
faces: 
total_faces: null
matched_faces: {}
friendly_name: Kitchen
device_class: face
```

Is this something that has been corrected with later custom_component? I will upgrade and test when I have a minute...
