### ISSUE TITLE
total_faces value returns to 0 between 2 scans

### ISSUE THREAD

**Issue by MimbaMonkeyHouse** [robmarkcole/HASS-Machinebox-Facebox#9]
@robmarkcole this behaviour was noticed on HA 70.1 with stock component and multiple cameras. The types of cameras are generic rather than local file.

In HA dev tools States, I can see the value of total_faces increase temporarily when a face is present. It quickly reverts back to 0 between scans.  It should really stay at the max value until the next scan, as this could be great for specific uses. An example would be for shop owners trying to track the number of customers present in their store at any time.
Here is the code used:
```
  - platform: facebox
    ip_address: 192.168.x.x
    port: 8080
    scan_interval: 30
    source:
      - entity_id: camera.garden
        name: Garden
```
And here is a capture of the presence detection entity's history showing the total_faces attribute reverting back to 0 in between 2 image captures:
![facebox_capture](https://user-images.githubusercontent.com/35156237/41714904-618738fa-7584-11e8-9716-de924bc5380c.jpeg)

Do other users notice the same with multiple camera setups?
Is it recommended to use the local_file camera component rather than the generic one in order to only initiate image processing when motion is detected?
